apps/users/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from users import views
from users.views import LoginView, RegisterView, LogoutView, PasswordView

urlpatterns = [
    url(r'^login/$', csrf_exempt(LoginView.as_view()), name='login'),
    url(r'^register/$', csrf_exempt(RegisterView.as_view()), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^confirm/$', views.user_confirm, name="confirm"),
    url(r'^info/$', views.info, name="info"),
    url(r'^password/$', PasswordView.as_view(), name="password"),
]

class_schedule/urls.py
from django.conf.urls import url, include

import xadmin
from main.views import IndexView

urlpatterns = [
    url(r'^admin/', xadmin.site.urls),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^main/', include('main.urls', namespace='main')),


    url(r'^index/$', IndexView.as_view()),
    url(r'^$', IndexView.as_view()),
]

templates/login/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>验证</title>
</head>
<body>
{{ message }}
</body>
</html>

templates/login/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/login_style.css' %}">

</head>
<body>
<div class="login-page">
    <form id="login-form" class="form" method="post" action="{% url 'user:login' %}">
        <input type="text" name="username" placeholder="用户名">
        <input type="password" name="password" placeholder="密码">
        <button type="submit" id="login">登　录</button>
        <div class="msg"><span>还没有账户？</span>
            <button>创建账户</button>
        </div>
        <div class="errmsg"><span>{{ massage }}</span></div>
    </form>
    <form id="register-form" class="form" method="post" action="{% url 'user:register' %}">
        <input type="text" name="username" placeholder="电子邮箱">
        <input type="password" name="password" placeholder="密码">
        <button type="submit" id="register">创　建</button>
        <div class="msg"><span>已有账户？</span>
            <button>去登录</button>
        </div>
    </form>
</div>

<script src="https://code.jquery.com/jquery-2.2.4.js"
        integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
        crossorigin="anonymous"></script>

<script>
    $(function () {
        $('#login').click(function () {
            console.log('登录')
        });

        $('#register').click(function () {
            console.log('注册')
        });

        $('.msg button').click(function () {
            console.log("tt");
            $('#register-form').toggle(300);
            $('#login-form').toggle(300);
            return false;
        });
    });
</script>
</body>
</html>

templates/login/password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <title>密码找回</title>
</head>
<style>
    * {
        box-sizing: border-box;
    }

    body, html {
        margin: 0;
        padding: 0;
    }

    #temp {
        width: 100%;
        background-color: #4CAF50;
        padding: 12px;
        color: white;
    }
</style>
<body>

<div id="temp">
    由于开发者时间有限，暂时未开放密码找回功能。
    <br>
    如果您确实忘记了密码，请在设置内点击反馈联系开发者。
    <br>
    QQ：776310072
    <br>Email：xxyangyoulin@gmail.com
</div>

</body>
</html>